services:
  - type: worker   # ✅ IMPORTANT CHANGE
    name: editorshub-aura
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py

    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: JOBS_CHANNEL_ID
        sync: false
      - key: EDITORS_COMMUNITY_ID
        sync: false
      - key: GOOGLE_SHEET_KEY
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
